# Generated by Django 2.1.5 on 2019-01-07 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gloomtracker_api', '0002_character'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uses', models.IntegerField(default=1)),
                ('description', models.TextField()),
                ('character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gloomtracker_api.Character')),
            ],
        ),
    ]
