# Generated by Django 2.1.5 on 2019-01-07 03:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gloomtracker_api', '0003_perk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField()),
                ('description', models.TextField()),
                ('additional_info', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
