# Generated by Django 2.1.5 on 2019-01-07 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gloomtracker_api', '0004_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gloomtracker_api.Character'),
        ),
    ]
