# Generated by Django 2.1.5 on 2019-01-07 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gloomtracker_api', '0006_items_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
